rootProject.name = 'payrollpilot'

dependencyResolutionManagement {
    versionCatalogs {
        libs {
            from(files("gradle/libs.versions.toml"))
        }
    }
}

include ':frontend'
include ':shared'
include ':services:api-gateway'
include ':services:payroll-api'
include ':services:approval'
include ':services:calculation'
include ':services:payment'